Repository i4BSolutions/hope-fuel, pull requests merged in 2025-09, with the labels that each got.

#832 Update air table error handling (v2.1.0.1)
  src/app/api/getUserId/route.js
  src/app/utilites/ExtendUser/checkPrfSubmit.js
  src/app/utilites/checkUserSubmit.js
Labels: bug-fix-release

#833 fix: time frame logic in wallet count api
  src/app/api/v1/wallets/assigned-wallets/get-by-agent-id/route.js
Labels: bug

#834 fix: wallet count on payment check page
  src/app/api/v1/wallets/assigned-wallets/get-by-agent-id/route.js
Labels: bug

#845 Bug Fix (v2.1.0.3)
  src/app/admin-panel/_components/exchangeRate/page.jsx
  src/app/api/v1/wallets/assigned-wallets/get-by-agent-id/route.js
Labels: bug-fix-release, production

#851 Bug Fix (v2.1.0.7)
  src/app/fundraisers/schema.js
Labels: bug-fix-release, development

#852 Bug Fix(v2.1.0.7)
  src/app/fundraisers/schema.js
Labels: bug-fix-release, staging

#853 Bug Fix(v2.1.0.7)
  amplify/team-provider-info.json
  src/app/utilites/createForm/fileHandler.js
Labels: bug-fix-release, production
